# Generated by Django 2.0.1 on 2018-02-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180215_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activation',
        ),
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
