# Generated by Django 2.0.1 on 2018-02-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('core', '0004_auto_20180218_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
