# Generated by Django 2.0.1 on 2018-02-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180220_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='День Рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purpose',
            field=models.TextField(blank=True, max_length=500, verbose_name='Цель на ближайшие 3 месяца'),
        ),
    ]
